version: '2'

networks:
  app-tier:
    driver: bridge

services:
  cassandra:
    image: 'cassandra:latest'
    networks:
      - app-tier
    expose: 
      - '9042'
    ports:
      - '9042:9042'
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    expose:
      - '5432'
    ports:
      - '5432:5432'
